var metricDimensionNames = {
	'usertype': 'userType',
	'sessioncount': 'sessionCount',
	'dayssincelastsession': 'daysSinceLastSession',
	'userdefinedvalue': 'userDefinedValue',
	'userbucket': 'userBucket',
	'visitortype': 'visitorType',
	'visitcount': 'visitCount',
	'sessiondurationbucket': 'sessionDurationBucket',
	'visitlength': 'visitLength',
	'referralpath': 'referralPath',
	'fullreferrer': 'fullReferrer',
	'campaign': 'campaign',
	'source': 'source',
	'medium': 'medium',
	'sourcemedium': 'sourceMedium',
	'keyword': 'keyword',
	'adcontent': 'adContent',
	'socialnetwork': 'socialNetwork',
	'hassocialsourcereferral': 'hasSocialSourceReferral',
	'campaigncode': 'campaignCode',
	'adgroup': 'adGroup',
	'adslot': 'adSlot',
	'addistributionnetwork': 'adDistributionNetwork',
	'admatchtype': 'adMatchType',
	'adkeywordmatchtype': 'adKeywordMatchType',
	'admatchedquery': 'adMatchedQuery',
	'adplacementdomain': 'adPlacementDomain',
	'adplacementurl': 'adPlacementUrl',
	'adformat': 'adFormat',
	'adtargetingtype': 'adTargetingType',
	'adtargetingoption': 'adTargetingOption',
	'addisplayurl': 'adDisplayUrl',
	'addestinationurl': 'adDestinationUrl',
	'adwordscustomerid': 'adwordsCustomerID',
	'adwordscampaignid': 'adwordsCampaignID',
	'adwordsadgroupid': 'adwordsAdGroupID',
	'adwordscreativeid': 'adwordsCreativeID',
	'adwordscriteriaid': 'adwordsCriteriaID',
	'adquerywordcount': 'adQueryWordCount',
	'istrueviewvideoad': 'isTrueViewVideoAd',
	'goalcompletionlocation': 'goalCompletionLocation',
	'goalpreviousstep1': 'goalPreviousStep1',
	'goalpreviousstep2': 'goalPreviousStep2',
	'goalpreviousstep3': 'goalPreviousStep3',
	'browser': 'browser',
	'browserversion': 'browserVersion',
	'operatingsystem': 'operatingSystem',
	'operatingsystemversion': 'operatingSystemVersion',
	'mobiledevicebranding': 'mobileDeviceBranding',
	'mobiledevicemodel': 'mobileDeviceModel',
	'mobileinputselector': 'mobileInputSelector',
	'mobiledeviceinfo': 'mobileDeviceInfo',
	'mobiledevicemarketingname': 'mobileDeviceMarketingName',
	'devicecategory': 'deviceCategory',
	'browsersize': 'browserSize',
	'datasource': 'dataSource',
	'continent': 'continent',
	'subcontinent': 'subContinent',
	'country': 'country',
	'region': 'region',
	'metro': 'metro',
	'city': 'city',
	'latitude': 'latitude',
	'longitude': 'longitude',
	'networkdomain': 'networkDomain',
	'networklocation': 'networkLocation',
	'cityid': 'cityId',
	'continentid': 'continentId',
	'countryisocode': 'countryIsoCode',
	'metroid': 'metroId',
	'regionid': 'regionId',
	'regionisocode': 'regionIsoCode',
	'subcontinentcode': 'subContinentCode',
	'flashversion': 'flashVersion',
	'javaenabled': 'javaEnabled',
	'language': 'language',
	'screencolors': 'screenColors',
	'sourcepropertydisplayname': 'sourcePropertyDisplayName',
	'sourcepropertytrackingid': 'sourcePropertyTrackingId',
	'screenresolution': 'screenResolution',
	'socialactivitycontenturl': 'socialActivityContentUrl',
	'hostname': 'hostname',
	'pagepath': 'pagePath',
	'pagepathlevel1': 'pagePathLevel1',
	'pagepathlevel2': 'pagePathLevel2',
	'pagepathlevel3': 'pagePathLevel3',
	'pagepathlevel4': 'pagePathLevel4',
	'pagetitle': 'pageTitle',
	'landingpagepath': 'landingPagePath',
	'secondpagepath': 'secondPagePath',
	'exitpagepath': 'exitPagePath',
	'previouspagepath': 'previousPagePath',
	'pagedepth': 'pageDepth',
	'landingcontentgroupxx': 'landingContentGroupXX',
	'previouscontentgroupxx': 'previousContentGroupXX',
	'contentgroupxx': 'contentGroupXX',
	'searchused': 'searchUsed',
	'searchkeyword': 'searchKeyword',
	'searchkeywordrefinement': 'searchKeywordRefinement',
	'searchcategory': 'searchCategory',
	'searchstartpage': 'searchStartPage',
	'searchdestinationpage': 'searchDestinationPage',
	'searchafterdestinationpage': 'searchAfterDestinationPage',
	'appinstallerid': 'appInstallerId',
	'appversion': 'appVersion',
	'appname': 'appName',
	'appid': 'appId',
	'screenname': 'screenName',
	'screendepth': 'screenDepth',
	'landingscreenname': 'landingScreenName',
	'exitscreenname': 'exitScreenName',
	'eventcategory': 'eventCategory',
	'eventaction': 'eventAction',
	'eventlabel': 'eventLabel',
	'transactionid': 'transactionId',
	'affiliation': 'affiliation',
	'sessionstotransaction': 'sessionsToTransaction',
	'daystotransaction': 'daysToTransaction',
	'productsku': 'productSku',
	'productname': 'productName',
	'productcategory': 'productCategory',
	'currencycode': 'currencyCode',
	'checkoutoptions': 'checkoutOptions',
	'internalpromotioncreative': 'internalPromotionCreative',
	'internalpromotionid': 'internalPromotionId',
	'internalpromotionname': 'internalPromotionName',
	'internalpromotionposition': 'internalPromotionPosition',
	'ordercouponcode': 'orderCouponCode',
	'productbrand': 'productBrand',
	'productcategoryhierarchy': 'productCategoryHierarchy',
	'productcategorylevelxx': 'productCategoryLevelXX',
	'productcouponcode': 'productCouponCode',
	'productlistname': 'productListName',
	'productlistposition': 'productListPosition',
	'productvariant': 'productVariant',
	'shoppingstage': 'shoppingStage',
	'visitstotransaction': 'visitsToTransaction',
	'socialinteractionnetwork': 'socialInteractionNetwork',
	'socialinteractionaction': 'socialInteractionAction',
	'socialinteractionnetworkaction': 'socialInteractionNetworkAction',
	'socialinteractiontarget': 'socialInteractionTarget',
	'socialengagementtype': 'socialEngagementType',
	'usertimingcategory': 'userTimingCategory',
	'usertiminglabel': 'userTimingLabel',
	'usertimingvariable': 'userTimingVariable',
	'exceptiondescription': 'exceptionDescription',
	'experimentid': 'experimentId',
	'experimentvariant': 'experimentVariant',
	'dimensionxx': 'dimensionXX',
	'customvarnamexx': 'customVarNameXX',
	'customvarvaluexx': 'customVarValueXX',
	'date': 'date',
	'year': 'year',
	'month': 'month',
	'week': 'week',
	'day': 'day',
	'hour': 'hour',
	'minute': 'minute',
	'nthmonth': 'nthMonth',
	'nthweek': 'nthWeek',
	'nthday': 'nthDay',
	'nthminute': 'nthMinute',
	'dayofweek': 'dayOfWeek',
	'dayofweekname': 'dayOfWeekName',
	'datehour': 'dateHour',
	'datehourminute': 'dateHourMinute',
	'yearmonth': 'yearMonth',
	'yearweek': 'yearWeek',
	'isoweek': 'isoWeek',
	'isoyear': 'isoYear',
	'isoyearisoweek': 'isoYearIsoWeek',
	'nthhour': 'nthHour',
	'dcmclickad': 'dcmClickAd',
	'dcmclickadid': 'dcmClickAdId',
	'dcmclickadtype': 'dcmClickAdType',
	'dcmclickadtypeid': 'dcmClickAdTypeId',
	'dcmclickadvertiser': 'dcmClickAdvertiser',
	'dcmclickadvertiserid': 'dcmClickAdvertiserId',
	'dcmclickcampaign': 'dcmClickCampaign',
	'dcmclickcampaignid': 'dcmClickCampaignId',
	'dcmclickcreativeid': 'dcmClickCreativeId',
	'dcmclickcreative': 'dcmClickCreative',
	'dcmclickrenderingid': 'dcmClickRenderingId',
	'dcmclickcreativetype': 'dcmClickCreativeType',
	'dcmclickcreativetypeid': 'dcmClickCreativeTypeId',
	'dcmclickcreativeversion': 'dcmClickCreativeVersion',
	'dcmclicksite': 'dcmClickSite',
	'dcmclicksiteid': 'dcmClickSiteId',
	'dcmclicksiteplacement': 'dcmClickSitePlacement',
	'dcmclicksiteplacementid': 'dcmClickSitePlacementId',
	'dcmclickspotid': 'dcmClickSpotId',
	'dcmfloodlightactivity': 'dcmFloodlightActivity',
	'dcmfloodlightactivityandgroup': 'dcmFloodlightActivityAndGroup',
	'dcmfloodlightactivitygroup': 'dcmFloodlightActivityGroup',
	'dcmfloodlightactivitygroupid': 'dcmFloodlightActivityGroupId',
	'dcmfloodlightactivityid': 'dcmFloodlightActivityId',
	'dcmfloodlightadvertiserid': 'dcmFloodlightAdvertiserId',
	'dcmfloodlightspotid': 'dcmFloodlightSpotId',
	'dcmlasteventad': 'dcmLastEventAd',
	'dcmlasteventadid': 'dcmLastEventAdId',
	'dcmlasteventadtype': 'dcmLastEventAdType',
	'dcmlasteventadtypeid': 'dcmLastEventAdTypeId',
	'dcmlasteventadvertiser': 'dcmLastEventAdvertiser',
	'dcmlasteventadvertiserid': 'dcmLastEventAdvertiserId',
	'dcmlasteventattributiontype': 'dcmLastEventAttributionType',
	'dcmlasteventcampaign': 'dcmLastEventCampaign',
	'dcmlasteventcampaignid': 'dcmLastEventCampaignId',
	'dcmlasteventcreativeid': 'dcmLastEventCreativeId',
	'dcmlasteventcreative': 'dcmLastEventCreative',
	'dcmlasteventrenderingid': 'dcmLastEventRenderingId',
	'dcmlasteventcreativetype': 'dcmLastEventCreativeType',
	'dcmlasteventcreativetypeid': 'dcmLastEventCreativeTypeId',
	'dcmlasteventcreativeversion': 'dcmLastEventCreativeVersion',
	'dcmlasteventsite': 'dcmLastEventSite',
	'dcmlasteventsiteid': 'dcmLastEventSiteId',
	'dcmlasteventsiteplacement': 'dcmLastEventSitePlacement',
	'dcmlasteventsiteplacementid': 'dcmLastEventSitePlacementId',
	'dcmlasteventspotid': 'dcmLastEventSpotId',
	'useragebracket': 'userAgeBracket',
	'usergender': 'userGender',
	'interestothercategory': 'interestOtherCategory',
	'interestaffinitycategory': 'interestAffinityCategory',
	'interestinmarketcategory': 'interestInMarketCategory',
	'visitoragebracket': 'visitorAgeBracket',
	'visitorgender': 'visitorGender',
	'acquisitioncampaign': 'acquisitionCampaign',
	'acquisitionmedium': 'acquisitionMedium',
	'acquisitionsource': 'acquisitionSource',
	'acquisitionsourcemedium': 'acquisitionSourceMedium',
	'acquisitiontrafficchannel': 'acquisitionTrafficChannel',
	'cohort': 'cohort',
	'cohortnthday': 'cohortNthDay',
	'cohortnthmonth': 'cohortNthMonth',
	'cohortnthweek': 'cohortNthWeek',
	'channelgrouping': 'channelGrouping',
	'correlationmodelid': 'correlationModelId',
	'queryproductid': 'queryProductId',
	'queryproductname': 'queryProductName',
	'queryproductvariation': 'queryProductVariation',
	'relatedproductid': 'relatedProductId',
	'relatedproductname': 'relatedProductName',
	'relatedproductvariation': 'relatedProductVariation',
	'dbmclickadvertiser': 'dbmClickAdvertiser',
	'dbmclickadvertiserid': 'dbmClickAdvertiserId',
	'dbmclickcreativeid': 'dbmClickCreativeId',
	'dbmclickexchange': 'dbmClickExchange',
	'dbmclickexchangeid': 'dbmClickExchangeId',
	'dbmclickinsertionorder': 'dbmClickInsertionOrder',
	'dbmclickinsertionorderid': 'dbmClickInsertionOrderId',
	'dbmclicklineitem': 'dbmClickLineItem',
	'dbmclicklineitemid': 'dbmClickLineItemId',
	'dbmclicksite': 'dbmClickSite',
	'dbmclicksiteid': 'dbmClickSiteId',
	'dbmlasteventadvertiser': 'dbmLastEventAdvertiser',
	'dbmlasteventadvertiserid': 'dbmLastEventAdvertiserId',
	'dbmlasteventcreativeid': 'dbmLastEventCreativeId',
	'dbmlasteventexchange': 'dbmLastEventExchange',
	'dbmlasteventexchangeid': 'dbmLastEventExchangeId',
	'dbmlasteventinsertionorder': 'dbmLastEventInsertionOrder',
	'dbmlasteventinsertionorderid': 'dbmLastEventInsertionOrderId',
	'dbmlasteventlineitem': 'dbmLastEventLineItem',
	'dbmlasteventlineitemid': 'dbmLastEventLineItemId',
	'dbmlasteventsite': 'dbmLastEventSite',
	'dbmlasteventsiteid': 'dbmLastEventSiteId',
	'dsadgroup': 'dsAdGroup',
	'dsadgroupid': 'dsAdGroupId',
	'dsadvertiser': 'dsAdvertiser',
	'dsadvertiserid': 'dsAdvertiserId',
	'dsagency': 'dsAgency',
	'dsagencyid': 'dsAgencyId',
	'dscampaign': 'dsCampaign',
	'dscampaignid': 'dsCampaignId',
	'dsengineaccount': 'dsEngineAccount',
	'dsengineaccountid': 'dsEngineAccountId',
	'dskeyword': 'dsKeyword',
	'dskeywordid': 'dsKeywordId',
	'users': 'users',
	'newusers': 'newUsers',
	'percentnewsessions': 'percentNewSessions',
	'1dayusers': '1dayUsers',
	'7dayusers': '7dayUsers',
	'14dayusers': '14dayUsers',
	'28dayusers': '28dayUsers',
	'30dayusers': '30dayUsers',
	'sessionsperuser': 'sessionsPerUser',
	'visitors': 'visitors',
	'newvisits': 'newVisits',
	'percentnewvisits': 'percentNewVisits',
	'sessions': 'sessions',
	'bounces': 'bounces',
	'bouncerate': 'bounceRate',
	'sessionduration': 'sessionDuration',
	'avgsessionduration': 'avgSessionDuration',
	'uniquedimensioncombinations': 'uniqueDimensionCombinations',
	'hits': 'hits',
	'visits': 'visits',
	'visitbouncerate': 'visitBounceRate',
	'organicsearches': 'organicSearches',
	'impressions': 'impressions',
	'adclicks': 'adClicks',
	'adcost': 'adCost',
	'cpm': 'CPM',
	'cpc': 'CPC',
	'ctr': 'CTR',
	'costpertransaction': 'costPerTransaction',
	'costpergoalconversion': 'costPerGoalConversion',
	'costperconversion': 'costPerConversion',
	'rpc': 'RPC',
	'roas': 'ROAS',
	'roi': 'ROI',
	'margin': 'margin',
	'goalxxstarts': 'goalXXStarts',
	'goalstartsall': 'goalStartsAll',
	'goalxxcompletions': 'goalXXCompletions',
	'goalcompletionsall': 'goalCompletionsAll',
	'goalxxvalue': 'goalXXValue',
	'goalvalueall': 'goalValueAll',
	'goalvaluepersession': 'goalValuePerSession',
	'goalxxconversionrate': 'goalXXConversionRate',
	'goalconversionrateall': 'goalConversionRateAll',
	'goalxxabandons': 'goalXXAbandons',
	'goalabandonsall': 'goalAbandonsAll',
	'goalxxabandonrate': 'goalXXAbandonRate',
	'goalabandonrateall': 'goalAbandonRateAll',
	'goalvaluepervisit': 'goalValuePerVisit',
	'pagevalue': 'pageValue',
	'entrances': 'entrances',
	'entrancerate': 'entranceRate',
	'pageviews': 'pageviews',
	'pageviewspersession': 'pageviewsPerSession',
	'uniquepageviews': 'uniquePageviews',
	'timeonpage': 'timeOnPage',
	'avgtimeonpage': 'avgTimeOnPage',
	'exits': 'exits',
	'exitrate': 'exitRate',
	'pageviewspervisit': 'pageviewsPerVisit',
	'contentgroupuniqueviewsxx': 'contentGroupUniqueViewsXX',
	'searchresultviews': 'searchResultViews',
	'searchuniques': 'searchUniques',
	'avgsearchresultviews': 'avgSearchResultViews',
	'searchsessions': 'searchSessions',
	'percentsessionswithsearch': 'percentSessionsWithSearch',
	'searchdepth': 'searchDepth',
	'avgsearchdepth': 'avgSearchDepth',
	'searchrefinements': 'searchRefinements',
	'percentsearchrefinements': 'percentSearchRefinements',
	'searchduration': 'searchDuration',
	'avgsearchduration': 'avgSearchDuration',
	'searchexits': 'searchExits',
	'searchexitrate': 'searchExitRate',
	'searchgoalxxconversionrate': 'searchGoalXXConversionRate',
	'searchgoalconversionrateall': 'searchGoalConversionRateAll',
	'goalvalueallpersearch': 'goalValueAllPerSearch',
	'searchvisits': 'searchVisits',
	'percentvisitswithsearch': 'percentVisitsWithSearch',
	'pageloadtime': 'pageLoadTime',
	'pageloadsample': 'pageLoadSample',
	'avgpageloadtime': 'avgPageLoadTime',
	'domainlookuptime': 'domainLookupTime',
	'avgdomainlookuptime': 'avgDomainLookupTime',
	'pagedownloadtime': 'pageDownloadTime',
	'avgpagedownloadtime': 'avgPageDownloadTime',
	'redirectiontime': 'redirectionTime',
	'avgredirectiontime': 'avgRedirectionTime',
	'serverconnectiontime': 'serverConnectionTime',
	'avgserverconnectiontime': 'avgServerConnectionTime',
	'serverresponsetime': 'serverResponseTime',
	'avgserverresponsetime': 'avgServerResponseTime',
	'speedmetricssample': 'speedMetricsSample',
	'dominteractivetime': 'domInteractiveTime',
	'avgdominteractivetime': 'avgDomInteractiveTime',
	'domcontentloadedtime': 'domContentLoadedTime',
	'avgdomcontentloadedtime': 'avgDomContentLoadedTime',
	'domlatencymetricssample': 'domLatencyMetricsSample',
	'screenviews': 'screenviews',
	'uniquescreenviews': 'uniqueScreenviews',
	'screenviewspersession': 'screenviewsPerSession',
	'timeonscreen': 'timeOnScreen',
	'avgscreenviewduration': 'avgScreenviewDuration',
	'uniqueappviews': 'uniqueAppviews',
	'totalevents': 'totalEvents',
	'uniqueevents': 'uniqueEvents',
	'eventvalue': 'eventValue',
	'avgeventvalue': 'avgEventValue',
	'sessionswithevent': 'sessionsWithEvent',
	'eventspersessionwithevent': 'eventsPerSessionWithEvent',
	'visitswithevent': 'visitsWithEvent',
	'eventspervisitwithevent': 'eventsPerVisitWithEvent',
	'transactions': 'transactions',
	'transactionspersession': 'transactionsPerSession',
	'transactionrevenue': 'transactionRevenue',
	'revenuepertransaction': 'revenuePerTransaction',
	'transactionrevenuepersession': 'transactionRevenuePerSession',
	'transactionshipping': 'transactionShipping',
	'transactiontax': 'transactionTax',
	'totalvalue': 'totalValue',
	'itemquantity': 'itemQuantity',
	'uniquepurchases': 'uniquePurchases',
	'revenueperitem': 'revenuePerItem',
	'itemrevenue': 'itemRevenue',
	'itemsperpurchase': 'itemsPerPurchase',
	'localtransactionrevenue': 'localTransactionRevenue',
	'localtransactionshipping': 'localTransactionShipping',
	'localtransactiontax': 'localTransactionTax',
	'localitemrevenue': 'localItemRevenue',
	'buytodetailrate': 'buyToDetailRate',
	'carttodetailrate': 'cartToDetailRate',
	'internalpromotionctr': 'internalPromotionCTR',
	'internalpromotionclicks': 'internalPromotionClicks',
	'internalpromotionviews': 'internalPromotionViews',
	'localproductrefundamount': 'localProductRefundAmount',
	'localrefundamount': 'localRefundAmount',
	'productaddstocart': 'productAddsToCart',
	'productcheckouts': 'productCheckouts',
	'productdetailviews': 'productDetailViews',
	'productlistctr': 'productListCTR',
	'productlistclicks': 'productListClicks',
	'productlistviews': 'productListViews',
	'productrefundamount': 'productRefundAmount',
	'productrefunds': 'productRefunds',
	'productremovesfromcart': 'productRemovesFromCart',
	'productrevenueperpurchase': 'productRevenuePerPurchase',
	'quantityaddedtocart': 'quantityAddedToCart',
	'quantitycheckedout': 'quantityCheckedOut',
	'quantityrefunded': 'quantityRefunded',
	'quantityremovedfromcart': 'quantityRemovedFromCart',
	'refundamount': 'refundAmount',
	'revenueperuser': 'revenuePerUser',
	'totalrefunds': 'totalRefunds',
	'transactionsperuser': 'transactionsPerUser',
	'transactionspervisit': 'transactionsPerVisit',
	'transactionrevenuepervisit': 'transactionRevenuePerVisit',
	'socialinteractions': 'socialInteractions',
	'uniquesocialinteractions': 'uniqueSocialInteractions',
	'socialinteractionspersession': 'socialInteractionsPerSession',
	'socialinteractionspervisit': 'socialInteractionsPerVisit',
	'usertimingvalue': 'userTimingValue',
	'usertimingsample': 'userTimingSample',
	'avgusertimingvalue': 'avgUserTimingValue',
	'exceptions': 'exceptions',
	'exceptionsperscreenview': 'exceptionsPerScreenview',
	'fatalexceptions': 'fatalExceptions',
	'fatalexceptionsperscreenview': 'fatalExceptionsPerScreenview',
	'metricxx': 'metricXX',
	'dcmfloodlightquantity': 'dcmFloodlightQuantity',
	'dcmfloodlightrevenue': 'dcmFloodlightRevenue',
	'dcmcpc': 'dcmCPC',
	'dcmctr': 'dcmCTR',
	'dcmclicks': 'dcmClicks',
	'dcmcost': 'dcmCost',
	'dcmimpressions': 'dcmImpressions',
	'dcmroas': 'dcmROAS',
	'dcmrpc': 'dcmRPC',
	'dcmmargin': 'dcmMargin',
	'adsenserevenue': 'adsenseRevenue',
	'adsenseadunitsviewed': 'adsenseAdUnitsViewed',
	'adsenseadsviewed': 'adsenseAdsViewed',
	'adsenseadsclicks': 'adsenseAdsClicks',
	'adsensepageimpressions': 'adsensePageImpressions',
	'adsensectr': 'adsenseCTR',
	'adsenseecpm': 'adsenseECPM',
	'adsenseexits': 'adsenseExits',
	'adsenseviewableimpressionpercent': 'adsenseViewableImpressionPercent',
	'adsensecoverage': 'adsenseCoverage',
	'adximpressions': 'adxImpressions',
	'adxcoverage': 'adxCoverage',
	'adxmonetizedpageviews': 'adxMonetizedPageviews',
	'adximpressionspersession': 'adxImpressionsPerSession',
	'adxviewableimpressionspercent': 'adxViewableImpressionsPercent',
	'adxclicks': 'adxClicks',
	'adxctr': 'adxCTR',
	'adxrevenue': 'adxRevenue',
	'adxrevenueper1000sessions': 'adxRevenuePer1000Sessions',
	'adxecpm': 'adxECPM',
	'dfpimpressions': 'dfpImpressions',
	'dfpcoverage': 'dfpCoverage',
	'dfpmonetizedpageviews': 'dfpMonetizedPageviews',
	'dfpimpressionspersession': 'dfpImpressionsPerSession',
	'dfpviewableimpressionspercent': 'dfpViewableImpressionsPercent',
	'dfpclicks': 'dfpClicks',
	'dfpctr': 'dfpCTR',
	'dfprevenue': 'dfpRevenue',
	'dfprevenueper1000sessions': 'dfpRevenuePer1000Sessions',
	'dfpecpm': 'dfpECPM',
	'backfillimpressions': 'backfillImpressions',
	'backfillcoverage': 'backfillCoverage',
	'backfillmonetizedpageviews': 'backfillMonetizedPageviews',
	'backfillimpressionspersession': 'backfillImpressionsPerSession',
	'backfillviewableimpressionspercent': 'backfillViewableImpressionsPercent',
	'backfillclicks': 'backfillClicks',
	'backfillctr': 'backfillCTR',
	'backfillrevenue': 'backfillRevenue',
	'backfillrevenueper1000sessions': 'backfillRevenuePer1000Sessions',
	'backfillecpm': 'backfillECPM',
	'cohortactiveusers': 'cohortActiveUsers',
	'cohortappviewsperuser': 'cohortAppviewsPerUser',
	'cohortappviewsperuserwithlifetimecriteria': 'cohortAppviewsPerUserWithLifetimeCriteria',
	'cohortgoalcompletionsperuser': 'cohortGoalCompletionsPerUser',
	'cohortgoalcompletionsperuserwithlifetimecriteria': 'cohortGoalCompletionsPerUserWithLifetimeCriteria',
	'cohortpageviewsperuser': 'cohortPageviewsPerUser',
	'cohortpageviewsperuserwithlifetimecriteria': 'cohortPageviewsPerUserWithLifetimeCriteria',
	'cohortretentionrate': 'cohortRetentionRate',
	'cohortrevenueperuser': 'cohortRevenuePerUser',
	'cohortrevenueperuserwithlifetimecriteria': 'cohortRevenuePerUserWithLifetimeCriteria',
	'cohortsessiondurationperuser': 'cohortSessionDurationPerUser',
	'cohortsessiondurationperuserwithlifetimecriteria': 'cohortSessionDurationPerUserWithLifetimeCriteria',
	'cohortsessionsperuser': 'cohortSessionsPerUser',
	'cohortsessionsperuserwithlifetimecriteria': 'cohortSessionsPerUserWithLifetimeCriteria',
	'cohorttotalusers': 'cohortTotalUsers',
	'cohorttotaluserswithlifetimecriteria': 'cohortTotalUsersWithLifetimeCriteria',
	'correlationscore': 'correlationScore',
	'queryproductquantity': 'queryProductQuantity',
	'relatedproductquantity': 'relatedProductQuantity',
	'dbmcpa': 'dbmCPA',
	'dbmcpc': 'dbmCPC',
	'dbmcpm': 'dbmCPM',
	'dbmctr': 'dbmCTR',
	'dbmclicks': 'dbmClicks',
	'dbmconversions': 'dbmConversions',
	'dbmcost': 'dbmCost',
	'dbmimpressions': 'dbmImpressions',
	'dbmroas': 'dbmROAS',
	'dscpc': 'dsCPC',
	'dsctr': 'dsCTR',
	'dsclicks': 'dsClicks',
	'dscost': 'dsCost',
	'dsimpressions': 'dsImpressions',
	'dsprofit': 'dsProfit',
	'dsreturnonadspend': 'dsReturnOnAdSpend',
	'dsrevenueperclick': 'dsRevenuePerClick'
}

var metricDimensionData = {
	"users" : "metrics",
	"newUsers" : "metrics",
	"percentNewSessions" : "metrics",
	"1dayUsers" : "metrics",
	"7dayUsers" : "metrics",
	"14dayUsers" : "metrics",
	"28dayUsers" : "metrics",
	"30dayUsers" : "metrics",
	"sessionsPerUser" : "metrics",
	"visitors" : "metrics",
	"newVisits" : "metrics",
	"percentNewVisits" : "metrics",
	"sessions" : "metrics",
	"bounces" : "metrics",
	"bounceRate" : "metrics",
	"sessionDuration" : "metrics",
	"avgSessionDuration" : "metrics",
	"uniqueDimensionCombinations" : "metrics",
	"hits" : "metrics",
	"visits" : "metrics",
	"visitBounceRate" : "metrics",
	"organicSearches" : "metrics",
	"impressions" : "metrics",
	"adClicks" : "metrics",
	"adCost" : "metrics",
	"CPM" : "metrics",
	"CPC" : "metrics",
	"CTR" : "metrics",
	"costPerTransaction" : "metrics",
	"costPerGoalConversion" : "metrics",
	"costPerConversion" : "metrics",
	"RPC" : "metrics",
	"ROAS" : "metrics",
	"ROI" : "metrics",
	"margin" : "metrics",
	"goalXXStarts" : "metrics",
	"goalStartsAll" : "metrics",
	"goalXXCompletions" : "metrics",
	"goalCompletionsAll" : "metrics",
	"goalXXValue" : "metrics",
	"goalValueAll" : "metrics",
	"goalValuePerSession" : "metrics",
	"goalXXConversionRate" : "metrics",
	"goalConversionRateAll" : "metrics",
	"goalXXAbandons" : "metrics",
	"goalAbandonsAll" : "metrics",
	"goalXXAbandonRate" : "metrics",
	"goalAbandonRateAll" : "metrics",
	"goalValuePerVisit" : "metrics",
	"pageValue" : "metrics",
	"entrances" : "metrics",
	"entranceRate" : "metrics",
	"pageviews" : "metrics",
	"pageviewsPerSession" : "metrics",
	"uniquePageviews" : "metrics",
	"timeOnPage" : "metrics",
	"avgTimeOnPage" : "metrics",
	"exits" : "metrics",
	"exitRate" : "metrics",
	"pageviewsPerVisit" : "metrics",
	"contentGroupUniqueViewsXX" : "metrics",
	"searchResultViews" : "metrics",
	"searchUniques" : "metrics",
	"avgSearchResultViews" : "metrics",
	"searchSessions" : "metrics",
	"percentSessionsWithSearch" : "metrics",
	"searchDepth" : "metrics",
	"avgSearchDepth" : "metrics",
	"searchRefinements" : "metrics",
	"percentSearchRefinements" : "metrics",
	"searchDuration" : "metrics",
	"avgSearchDuration" : "metrics",
	"searchExits" : "metrics",
	"searchExitRate" : "metrics",
	"searchGoalXXConversionRate" : "metrics",
	"searchGoalConversionRateAll" : "metrics",
	"goalValueAllPerSearch" : "metrics",
	"searchVisits" : "metrics",
	"percentVisitsWithSearch" : "metrics",
	"pageLoadTime" : "metrics",
	"pageLoadSample" : "metrics",
	"avgPageLoadTime" : "metrics",
	"domainLookupTime" : "metrics",
	"avgDomainLookupTime" : "metrics",
	"pageDownloadTime" : "metrics",
	"avgPageDownloadTime" : "metrics",
	"redirectionTime" : "metrics",
	"avgRedirectionTime" : "metrics",
	"serverConnectionTime" : "metrics",
	"avgServerConnectionTime" : "metrics",
	"serverResponseTime" : "metrics",
	"avgServerResponseTime" : "metrics",
	"speedMetricsSample" : "metrics",
	"domInteractiveTime" : "metrics",
	"avgDomInteractiveTime" : "metrics",
	"domContentLoadedTime" : "metrics",
	"avgDomContentLoadedTime" : "metrics",
	"domLatencyMetricsSample" : "metrics",
	"screenviews" : "metrics",
	"uniqueScreenviews" : "metrics",
	"screenviewsPerSession" : "metrics",
	"timeOnScreen" : "metrics",
	"avgScreenviewDuration" : "metrics",
	"uniqueAppviews" : "metrics",
	"totalEvents" : "metrics",
	"uniqueEvents" : "metrics",
	"eventValue" : "metrics",
	"avgEventValue" : "metrics",
	"sessionsWithEvent" : "metrics",
	"eventsPerSessionWithEvent" : "metrics",
	"visitsWithEvent" : "metrics",
	"eventsPerVisitWithEvent" : "metrics",
	"transactions" : "metrics",
	"transactionsPerSession" : "metrics",
	"transactionRevenue" : "metrics",
	"revenuePerTransaction" : "metrics",
	"transactionRevenuePerSession" : "metrics",
	"transactionShipping" : "metrics",
	"transactionTax" : "metrics",
	"totalValue" : "metrics",
	"itemQuantity" : "metrics",
	"uniquePurchases" : "metrics",
	"revenuePerItem" : "metrics",
	"itemRevenue" : "metrics",
	"itemsPerPurchase" : "metrics",
	"localTransactionRevenue" : "metrics",
	"localTransactionShipping" : "metrics",
	"localTransactionTax" : "metrics",
	"localItemRevenue" : "metrics",
	"buyToDetailRate" : "metrics",
	"cartToDetailRate" : "metrics",
	"internalPromotionCTR" : "metrics",
	"internalPromotionClicks" : "metrics",
	"internalPromotionViews" : "metrics",
	"localProductRefundAmount" : "metrics",
	"localRefundAmount" : "metrics",
	"productAddsToCart" : "metrics",
	"productCheckouts" : "metrics",
	"productDetailViews" : "metrics",
	"productListCTR" : "metrics",
	"productListClicks" : "metrics",
	"productListViews" : "metrics",
	"productRefundAmount" : "metrics",
	"productRefunds" : "metrics",
	"productRemovesFromCart" : "metrics",
	"productRevenuePerPurchase" : "metrics",
	"quantityAddedToCart" : "metrics",
	"quantityCheckedOut" : "metrics",
	"quantityRefunded" : "metrics",
	"quantityRemovedFromCart" : "metrics",
	"refundAmount" : "metrics",
	"revenuePerUser" : "metrics",
	"totalRefunds" : "metrics",
	"transactionsPerUser" : "metrics",
	"transactionsPerVisit" : "metrics",
	"transactionRevenuePerVisit" : "metrics",
	"socialInteractions" : "metrics",
	"uniqueSocialInteractions" : "metrics",
	"socialInteractionsPerSession" : "metrics",
	"socialInteractionsPerVisit" : "metrics",
	"userTimingValue" : "metrics",
	"userTimingSample" : "metrics",
	"avgUserTimingValue" : "metrics",
	"exceptions" : "metrics",
	"exceptionsPerScreenview" : "metrics",
	"fatalExceptions" : "metrics",
	"fatalExceptionsPerScreenview" : "metrics",
	"metricXX" : "metrics",
	"dcmFloodlightQuantity" : "metrics",
	"dcmFloodlightRevenue" : "metrics",
	"dcmCPC" : "metrics",
	"dcmCTR" : "metrics",
	"dcmClicks" : "metrics",
	"dcmCost" : "metrics",
	"dcmImpressions" : "metrics",
	"dcmROAS" : "metrics",
	"dcmRPC" : "metrics",
	"dcmMargin" : "metrics",
	"adsenseRevenue" : "metrics",
	"adsenseAdUnitsViewed" : "metrics",
	"adsenseAdsViewed" : "metrics",
	"adsenseAdsClicks" : "metrics",
	"adsensePageImpressions" : "metrics",
	"adsenseCTR" : "metrics",
	"adsenseECPM" : "metrics",
	"adsenseExits" : "metrics",
	"adsenseViewableImpressionPercent" : "metrics",
	"adsenseCoverage" : "metrics",
	"adxImpressions" : "metrics",
	"adxCoverage" : "metrics",
	"adxMonetizedPageviews" : "metrics",
	"adxImpressionsPerSession" : "metrics",
	"adxViewableImpressionsPercent" : "metrics",
	"adxClicks" : "metrics",
	"adxCTR" : "metrics",
	"adxRevenue" : "metrics",
	"adxRevenuePer1000Sessions" : "metrics",
	"adxECPM" : "metrics",
	"dfpImpressions" : "metrics",
	"dfpCoverage" : "metrics",
	"dfpMonetizedPageviews" : "metrics",
	"dfpImpressionsPerSession" : "metrics",
	"dfpViewableImpressionsPercent" : "metrics",
	"dfpClicks" : "metrics",
	"dfpCTR" : "metrics",
	"dfpRevenue" : "metrics",
	"dfpRevenuePer1000Sessions" : "metrics",
	"dfpECPM" : "metrics",
	"backfillImpressions" : "metrics",
	"backfillCoverage" : "metrics",
	"backfillMonetizedPageviews" : "metrics",
	"backfillImpressionsPerSession" : "metrics",
	"backfillViewableImpressionsPercent" : "metrics",
	"backfillClicks" : "metrics",
	"backfillCTR" : "metrics",
	"backfillRevenue" : "metrics",
	"backfillRevenuePer1000Sessions" : "metrics",
	"backfillECPM" : "metrics",
	"cohortActiveUsers" : "metrics",
	"cohortAppviewsPerUser" : "metrics",
	"cohortAppviewsPerUserWithLifetimeCriteria" : "metrics",
	"cohortGoalCompletionsPerUser" : "metrics",
	"cohortGoalCompletionsPerUserWithLifetimeCriteria" : "metrics",
	"cohortPageviewsPerUser" : "metrics",
	"cohortPageviewsPerUserWithLifetimeCriteria" : "metrics",
	"cohortRetentionRate" : "metrics",
	"cohortRevenuePerUser" : "metrics",
	"cohortRevenuePerUserWithLifetimeCriteria" : "metrics",
	"cohortSessionDurationPerUser" : "metrics",
	"cohortSessionDurationPerUserWithLifetimeCriteria" : "metrics",
	"cohortSessionsPerUser" : "metrics",
	"cohortSessionsPerUserWithLifetimeCriteria" : "metrics",
	"cohortTotalUsers" : "metrics",
	"cohortTotalUsersWithLifetimeCriteria" : "metrics",
	"correlationScore" : "metrics",
	"queryProductQuantity" : "metrics",
	"relatedProductQuantity" : "metrics",
	"dbmCPA" : "metrics",
	"dbmCPC" : "metrics",
	"dbmCPM" : "metrics",
	"dbmCTR" : "metrics",
	"dbmClicks" : "metrics",
	"dbmConversions" : "metrics",
	"dbmCost" : "metrics",
	"dbmImpressions" : "metrics",
	"dbmROAS" : "metrics",
	"dsCPC" : "metrics",
	"dsCTR" : "metrics",
	"dsClicks" : "metrics",
	"dsCost" : "metrics",
	"dsImpressions" : "metrics",
	"dsProfit" : "metrics",
	"dsReturnOnAdSpend" : "metrics",
	"dsRevenuePerClick" : "metrics",
	"userType" : "dimensions",
	"sessionCount" : "dimensions",
	"daysSinceLastSession" : "dimensions",
	"userDefinedValue" : "dimensions",
	"userBucket" : "dimensions",
	"visitorType" : "dimensions",
	"visitCount" : "dimensions",
	"sessionDurationBucket" : "dimensions",
	"visitLength" : "dimensions",
	"referralPath" : "dimensions",
	"fullReferrer" : "dimensions",
	"campaign" : "dimensions",
	"source" : "dimensions",
	"medium" : "dimensions",
	"sourceMedium" : "dimensions",
	"keyword" : "dimensions",
	"adContent" : "dimensions",
	"socialNetwork" : "dimensions",
	"hasSocialSourceReferral" : "dimensions",
	"campaignCode" : "dimensions",
	"adGroup" : "dimensions",
	"adSlot" : "dimensions",
	"adDistributionNetwork" : "dimensions",
	"adMatchType" : "dimensions",
	"adKeywordMatchType" : "dimensions",
	"adMatchedQuery" : "dimensions",
	"adPlacementDomain" : "dimensions",
	"adPlacementUrl" : "dimensions",
	"adFormat" : "dimensions",
	"adTargetingType" : "dimensions",
	"adTargetingOption" : "dimensions",
	"adDisplayUrl" : "dimensions",
	"adDestinationUrl" : "dimensions",
	"adwordsCustomerID" : "dimensions",
	"adwordsCampaignID" : "dimensions",
	"adwordsAdGroupID" : "dimensions",
	"adwordsCreativeID" : "dimensions",
	"adwordsCriteriaID" : "dimensions",
	"adQueryWordCount" : "dimensions",
	"isTrueViewVideoAd" : "dimensions",
	"goalCompletionLocation" : "dimensions",
	"goalPreviousStep1" : "dimensions",
	"goalPreviousStep2" : "dimensions",
	"goalPreviousStep3" : "dimensions",
	"browser" : "dimensions",
	"browserVersion" : "dimensions",
	"operatingSystem" : "dimensions",
	"operatingSystemVersion" : "dimensions",
	"mobileDeviceBranding" : "dimensions",
	"mobileDeviceModel" : "dimensions",
	"mobileInputSelector" : "dimensions",
	"mobileDeviceInfo" : "dimensions",
	"mobileDeviceMarketingName" : "dimensions",
	"deviceCategory" : "dimensions",
	"browserSize" : "dimensions",
	"dataSource" : "dimensions",
	"continent" : "dimensions",
	"subContinent" : "dimensions",
	"country" : "dimensions",
	"region" : "dimensions",
	"metro" : "dimensions",
	"city" : "dimensions",
	"latitude" : "dimensions",
	"longitude" : "dimensions",
	"networkDomain" : "dimensions",
	"networkLocation" : "dimensions",
	"cityId" : "dimensions",
	"continentId" : "dimensions",
	"countryIsoCode" : "dimensions",
	"metroId" : "dimensions",
	"regionId" : "dimensions",
	"regionIsoCode" : "dimensions",
	"subContinentCode" : "dimensions",
	"flashVersion" : "dimensions",
	"javaEnabled" : "dimensions",
	"language" : "dimensions",
	"screenColors" : "dimensions",
	"sourcePropertyDisplayName" : "dimensions",
	"sourcePropertyTrackingId" : "dimensions",
	"screenResolution" : "dimensions",
	"socialActivityContentUrl" : "dimensions",
	"hostname" : "dimensions",
	"pagePath" : "dimensions",
	"pagePathLevel1" : "dimensions",
	"pagePathLevel2" : "dimensions",
	"pagePathLevel3" : "dimensions",
	"pagePathLevel4" : "dimensions",
	"pageTitle" : "dimensions",
	"landingPagePath" : "dimensions",
	"secondPagePath" : "dimensions",
	"exitPagePath" : "dimensions",
	"previousPagePath" : "dimensions",
	"pageDepth" : "dimensions",
	"landingContentGroupXX" : "dimensions",
	"previousContentGroupXX" : "dimensions",
	"contentGroupXX" : "dimensions",
	"searchUsed" : "dimensions",
	"searchKeyword" : "dimensions",
	"searchKeywordRefinement" : "dimensions",
	"searchCategory" : "dimensions",
	"searchStartPage" : "dimensions",
	"searchDestinationPage" : "dimensions",
	"searchAfterDestinationPage" : "dimensions",
	"appInstallerId" : "dimensions",
	"appVersion" : "dimensions",
	"appName" : "dimensions",
	"appId" : "dimensions",
	"screenName" : "dimensions",
	"screenDepth" : "dimensions",
	"landingScreenName" : "dimensions",
	"exitScreenName" : "dimensions",
	"eventCategory" : "dimensions",
	"eventAction" : "dimensions",
	"eventLabel" : "dimensions",
	"transactionId" : "dimensions",
	"affiliation" : "dimensions",
	"sessionsToTransaction" : "dimensions",
	"daysToTransaction" : "dimensions",
	"productSku" : "dimensions",
	"productName" : "dimensions",
	"productCategory" : "dimensions",
	"currencyCode" : "dimensions",
	"checkoutOptions" : "dimensions",
	"internalPromotionCreative" : "dimensions",
	"internalPromotionId" : "dimensions",
	"internalPromotionName" : "dimensions",
	"internalPromotionPosition" : "dimensions",
	"orderCouponCode" : "dimensions",
	"productBrand" : "dimensions",
	"productCategoryHierarchy" : "dimensions",
	"productCategoryLevelXX" : "dimensions",
	"productCouponCode" : "dimensions",
	"productListName" : "dimensions",
	"productListPosition" : "dimensions",
	"productVariant" : "dimensions",
	"shoppingStage" : "dimensions",
	"visitsToTransaction" : "dimensions",
	"socialInteractionNetwork" : "dimensions",
	"socialInteractionAction" : "dimensions",
	"socialInteractionNetworkAction" : "dimensions",
	"socialInteractionTarget" : "dimensions",
	"socialEngagementType" : "dimensions",
	"userTimingCategory" : "dimensions",
	"userTimingLabel" : "dimensions",
	"userTimingVariable" : "dimensions",
	"exceptionDescription" : "dimensions",
	"experimentId" : "dimensions",
	"experimentVariant" : "dimensions",
	"dimensionXX" : "dimensions",
	"customVarNameXX" : "dimensions",
	"customVarValueXX" : "dimensions",
	"date" : "dimensions",
	"year" : "dimensions",
	"month" : "dimensions",
	"week" : "dimensions",
	"day" : "dimensions",
	"hour" : "dimensions",
	"minute" : "dimensions",
	"nthMonth" : "dimensions",
	"nthWeek" : "dimensions",
	"nthDay" : "dimensions",
	"nthMinute" : "dimensions",
	"dayOfWeek" : "dimensions",
	"dayOfWeekName" : "dimensions",
	"dateHour" : "dimensions",
	"dateHourMinute" : "dimensions",
	"yearMonth" : "dimensions",
	"yearWeek" : "dimensions",
	"isoWeek" : "dimensions",
	"isoYear" : "dimensions",
	"isoYearIsoWeek" : "dimensions",
	"nthHour" : "dimensions",
	"dcmClickAd" : "dimensions",
	"dcmClickAdId" : "dimensions",
	"dcmClickAdType" : "dimensions",
	"dcmClickAdTypeId" : "dimensions",
	"dcmClickAdvertiser" : "dimensions",
	"dcmClickAdvertiserId" : "dimensions",
	"dcmClickCampaign" : "dimensions",
	"dcmClickCampaignId" : "dimensions",
	"dcmClickCreativeId" : "dimensions",
	"dcmClickCreative" : "dimensions",
	"dcmClickRenderingId" : "dimensions",
	"dcmClickCreativeType" : "dimensions",
	"dcmClickCreativeTypeId" : "dimensions",
	"dcmClickCreativeVersion" : "dimensions",
	"dcmClickSite" : "dimensions",
	"dcmClickSiteId" : "dimensions",
	"dcmClickSitePlacement" : "dimensions",
	"dcmClickSitePlacementId" : "dimensions",
	"dcmClickSpotId" : "dimensions",
	"dcmFloodlightActivity" : "dimensions",
	"dcmFloodlightActivityAndGroup" : "dimensions",
	"dcmFloodlightActivityGroup" : "dimensions",
	"dcmFloodlightActivityGroupId" : "dimensions",
	"dcmFloodlightActivityId" : "dimensions",
	"dcmFloodlightAdvertiserId" : "dimensions",
	"dcmFloodlightSpotId" : "dimensions",
	"dcmLastEventAd" : "dimensions",
	"dcmLastEventAdId" : "dimensions",
	"dcmLastEventAdType" : "dimensions",
	"dcmLastEventAdTypeId" : "dimensions",
	"dcmLastEventAdvertiser" : "dimensions",
	"dcmLastEventAdvertiserId" : "dimensions",
	"dcmLastEventAttributionType" : "dimensions",
	"dcmLastEventCampaign" : "dimensions",
	"dcmLastEventCampaignId" : "dimensions",
	"dcmLastEventCreativeId" : "dimensions",
	"dcmLastEventCreative" : "dimensions",
	"dcmLastEventRenderingId" : "dimensions",
	"dcmLastEventCreativeType" : "dimensions",
	"dcmLastEventCreativeTypeId" : "dimensions",
	"dcmLastEventCreativeVersion" : "dimensions",
	"dcmLastEventSite" : "dimensions",
	"dcmLastEventSiteId" : "dimensions",
	"dcmLastEventSitePlacement" : "dimensions",
	"dcmLastEventSitePlacementId" : "dimensions",
	"dcmLastEventSpotId" : "dimensions",
	"userAgeBracket" : "dimensions",
	"userGender" : "dimensions",
	"interestOtherCategory" : "dimensions",
	"interestAffinityCategory" : "dimensions",
	"interestInMarketCategory" : "dimensions",
	"visitorAgeBracket" : "dimensions",
	"visitorGender" : "dimensions",
	"acquisitionCampaign" : "dimensions",
	"acquisitionMedium" : "dimensions",
	"acquisitionSource" : "dimensions",
	"acquisitionSourceMedium" : "dimensions",
	"acquisitionTrafficChannel" : "dimensions",
	"cohort" : "dimensions",
	"cohortNthDay" : "dimensions",
	"cohortNthMonth" : "dimensions",
	"cohortNthWeek" : "dimensions",
	"channelGrouping" : "dimensions",
	"correlationModelId" : "dimensions",
	"queryProductId" : "dimensions",
	"queryProductName" : "dimensions",
	"queryProductVariation" : "dimensions",
	"relatedProductId" : "dimensions",
	"relatedProductName" : "dimensions",
	"relatedProductVariation" : "dimensions",
	"dbmClickAdvertiser" : "dimensions",
	"dbmClickAdvertiserId" : "dimensions",
	"dbmClickCreativeId" : "dimensions",
	"dbmClickExchange" : "dimensions",
	"dbmClickExchangeId" : "dimensions",
	"dbmClickInsertionOrder" : "dimensions",
	"dbmClickInsertionOrderId" : "dimensions",
	"dbmClickLineItem" : "dimensions",
	"dbmClickLineItemId" : "dimensions",
	"dbmClickSite" : "dimensions",
	"dbmClickSiteId" : "dimensions",
	"dbmLastEventAdvertiser" : "dimensions",
	"dbmLastEventAdvertiserId" : "dimensions",
	"dbmLastEventCreativeId" : "dimensions",
	"dbmLastEventExchange" : "dimensions",
	"dbmLastEventExchangeId" : "dimensions",
	"dbmLastEventInsertionOrder" : "dimensions",
	"dbmLastEventInsertionOrderId" : "dimensions",
	"dbmLastEventLineItem" : "dimensions",
	"dbmLastEventLineItemId" : "dimensions",
	"dbmLastEventSite" : "dimensions",
	"dbmLastEventSiteId" : "dimensions",
	"dsAdGroup" : "dimensions",
	"dsAdGroupId" : "dimensions",
	"dsAdvertiser" : "dimensions",
	"dsAdvertiserId" : "dimensions",
	"dsAgency" : "dimensions",
	"dsAgencyId" : "dimensions",
	"dsCampaign" : "dimensions",
	"dsCampaignId" : "dimensions",
	"dsEngineAccount" : "dimensions",
	"dsEngineAccountId" : "dimensions",
	"dsKeyword" : "dimensions",
	"dsKeywordId" : "dimensions"
}

module.exports = {
	generateApiName: function(name) {
		return `ga:${name}`;
	},
	sortMetricsDimensions: function(values) {
		var that = this;

		var result = {
			metrics: [],
			dimensions: []
		}

		values.forEach(function(value){
			value = that.fixName(value);
			if(!(value in metricDimensionData)) {
				throw new Error(`Unknown metric or dimension "${value}"!`);
			}
			result[metricDimensionData[value]].push(value);
		});
		
		return result;
	},
	fixName: function(name) {
		name = name.toLowerCase();
		if(!(name in metricDimensionNames)) {
			return name;
		}
		return metricDimensionNames[name];
	}
};
